### ISSUE TITLE
multiple comparisons

### ISSUE THREAD

**Issue by patriciamar** [adelahladka/difNLR#15]
Kdyz se ve funkci ddfMLR zada p.adjust.method="none", zda se, ze hvezdicky (signifikance) jsou urceny dle testu s (BH?) korekci. Zlobi pak take vypsani DDF polozek: Ma-li  polozka signifikantni DDF bez korekce, ale nesignifikantni s korekci, v zaveru nahlasi, ze tam neni zadna DDF polozka. Podobne vykresleni plotu: vyse zminena polozka se vykresli bez DDF.

Priklad:
group <- abs((dataHCI[, "gender"]=="F"))
(x <- ddfMLR(data, group, focal.name = 1, CR, type = "both", p.adjust.method = "none"))
# Item 12 bez hvezdicky, Item 19 ma jen jednu hvezdicku.
# Item 12 neni v seznamu DDF polozek
plot(x, item = 12)  # nevykresli jako DDF

**Comment by adelahladka** [comment]
Opraveno, jednalo se o překlep :) Díky
